### ISSUE TITLE
Forward / Back browser options

### ISSUE THREAD

**Issue by nuna-alan** [filipuic/playme#15]
It'd really be handy to be able to use browser style "forward & back" buttons when navigating the app. Sometimes you click into an album and just wanna go back up to the Artist level.

**Comment by filipnbc** [comment]
Seems like there is such a possibility in electron: https://github.com/electron/electron/pull/4843/files 
Will have a look. Would be really handy!

**Comment by filipnbc** [comment]
Actually even VsCode doesn't have it, as it is not yet supported by js/electron. 
https://github.com/electron/electron/issues/2683 
https://github.com/Microsoft/vscode/issues/40526
