### ISSUE TITLE
desktop file does not pass validation

### ISSUE THREAD

**Issue by probonopd** [filipuic/playme#7]
```
/tmp/.mount_appimauvr7Zt/playme.desktop: error: value "music;" for key "Categories" in group "Desktop Entry" contains an unregistered value "music"; values extending the format should start with "X-"
/tmp/.mount_appimauvr7Zt/playme.desktop: hint: value "music;" for key "Categories" in group "Desktop Entry" does not contain a registered main category; application might only show up in a "catch-all" section of the application menu
```

Please use `AudioVideo;` instead of `music;`

References:
* https://github.com/AppImage/appimage.github.io/pull/730
* https://github.com/AppImage/appimage.github.io/issues/2

**Comment by probonopd** [comment]
Thanks for merging. Please let me know once a version containing this fix is available on https://github.com/filipuic/playme/releases. Thank you very much.

**Comment by filipnbc** [comment]
@probonopd Just release the v1.0.1 with this fix in: 
https://github.com/filipuic/playme/releases/tag/v1.0.1 
Thank you!
